option('with_fp16', type: 'feature', value: 'disabled')
option('with_openmp', type: 'feature', value: 'disabled')
option('with_threads', type: 'feature', value: 'disabled')
option('with_zfp', type: 'feature', value: 'disabled')
option('with_piz', type: 'feature', value: 'enabled')
option('zlib_impl', type: 'combo', choices: ['miniz', 'nanozlib', 'stb', 'zlib', 'zlib-ng'], value: 'miniz')
option('build_examples', type: 'boolean', value: false)
option('build_exrview', type: 'boolean', value: false)
option('build_gl_examples', type: 'boolean', value: false)
